[project]
name = "weathercli"
version = "0.1.0"
description = "Weather app built on Openweather API using Textual"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "certifi==2026.4.22",
    "charset-normalizer==3.4.7",
    "dataclasses>=0.8",
    "dotenv>=0.9.9",
    "humanize>=4.15.0",
    "idna==3.13",
    "linkify-it-py==2.1.0",
    "markdown-it-py==4.0.0",
    "mdit-py-plugins==0.5.0",
    "mdurl==0.1.2",
    "platformdirs==4.9.6",
    "pygments==2.20.0",
    "requests==2.33.1",
    "rich==15.0.0",
    "textual==8.2.4",
    "timezonefinder>=8.2.0",
    "typing-extensions==4.15.0",
    "tzdata>=2026.2",
    "uc-micro-py==2.0.0",
    "urllib3==2.6.3",
]
